#!/usr/bin/env python3
"""Embed the shipped frontend for Arduino; --check verifies reproducibility."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = {
    "index_html": "index.html",
    "app_js_gz": "assets/app.js.gz",
    "index_css_gz": "assets/index.css.gz",
}


def render():
    result = ["// Generated by tools/generate_arduino_assets.py. Do not edit.", "#pragma once"]
    for name, path in ASSETS.items():
        data = (ROOT / "frontend/dist" / path).read_bytes()
        result.append(f"static const uint8_t {name}_start[] = {{")
        for offset in range(0, len(data), 16):
            result.append("    " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 16]) + ",")
        result.extend(["};", f"#define {name}_end ({name}_start + sizeof({name}_start))"])
    return "\n".join(result) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "src/arduino/webui_assets.h"
    content = render()
    if args.check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit("Arduino assets are stale; run tools/generate_arduino_assets.py")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
